workflows:
  my_workflow:
    name: My Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'dist-ios'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Code signing
        script: |
          xcode-project use-profiles
          xcode-project use-certificates
          xcode-project build-ipa --scheme "Runner" --configuration "Release"
    artifacts:
      - build/ios/ipa
    publishing:
      email:
        recipients:
          - ro.28745.maydana@gmail.com
        notify:
          success: true
          failure: true