workflows:
  my_workflow:
    name: My Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - profile_reference
        certificates:
          - certificate_reference
    integrations:
      app_store_connect:  app-store-connect
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'dist-ios'
          include: true
          source: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Run tests
        script: |
          flutter test
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
          --build-name=1.1.0 \
          --build-number=1 \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - ro.28745.maydana@gmail.com
        notify:
          success: true
          failure: true